spring.application.name=payment-service
outbox.poll-interval=5000
# Брокер
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

# Producer — сериализация в JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer — десериализация из JSON
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.properties.spring.json.type.mapping=\
paymentProcessed:by.shaaldy.paymentservice.messaging.event.payment.PaymentProcessedEvent,\
refundProcessed:by.shaaldy.paymentservice.messaging.event.refund.RefundProcessedEvent

spring.kafka.consumer.properties.spring.json.type.mapping=\
orderCreated:by.shaaldy.paymentservice.messaging.event.payment.OrderCreatedEvent,\
orderCancelled:by.shaaldy.paymentservice.messaging.event.refund.OrderCancelledEvent

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/payment_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:payment_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:payment_pass}